### PR TITLE
Rename licence to license

### PR DESCRIPTION
**Pull request by mgsloan**
Just a little fix.

Entirely unrelated side note / questions: I really like your site and generator.  I also want to minimize bytes transferred, have static sizes for images, etc.  I was dabbling with starting a Hakyll site, but I think I might prefer this more minimal generator approach.  I also like how the theme reminds me of Tufte's books.  So yeah, I'm pretty stoked on it.

* Do you mind if I copy the layout for my own site?  It may well begin to deviate, but initially it would look very similar, but of course different content

* Do you mind if my site repo forks off of yours?  I'm thinking that this might make it easier for me to update to changes you make to the generator, and vice versa.

Thanks!

### CODE REVIEW

**Comment by mgsloan** [comment]
Crap, the branch name I used is wrong, but can't change it after opening the PR.  Oh well

**Comment by mgsloan** [comment]
On second thought, this is pretty clearly "copyleft", so going to precede with adapting this.  Thanks for making the code for this available!

**Comment by ruuda** [comment]
Thank you for taking the time to open a PR. As far as I am aware, “[licence](https://dictionary.cambridge.org/dictionary/english/licence)” is British English and “[license](https://dictionary.cambridge.org/dictionary/english/license)” is American English. I use British English in my posts, but it is hard to remain consistent everywhere. Is there any benefit to naming it `license` over `licence` (tooling discovering it more easily maybe)?

> Entirely unrelated side note / questions: I really like your site and generator. I also want to minimize bytes transferred, have static sizes for images, etc. I was dabbling with starting a Hakyll site, but I think I might prefer this more minimal generator approach. I also like how the theme reminds me of Tufte's books. So yeah, I'm pretty stoked on it.
>
> * Do you mind if I copy the layout for my own site? It may well begin to deviate, but initially it would look very similar, but of course different content
>
> * Do you mind if my site repo forks off of yours? I'm thinking that this might make it easier for me to update to changes you make to the generator, and vice versa.

Thanks for the kind words! It is free software, go ahead and copy it, that why it is here in the first place. It would be nice if you could give it a touch of your own (maybe change the accent colour, or the font), although the license does not require it.

**Comment by mgsloan** [comment]
Ahh, I did not realize that `licence` is a valid spelling.  My mistake!

> It is free software, go ahead and copy it, that why it is here in the first place.

Great, thanks!

>  It would be nice if you could give it a touch of your own (maybe change the accent colour, or the font), although the license does not require it.

Yep, I certainly will do that!  I quite like the accent color, though, as said it reminds me of Tufte's books.  I will definitely be changing things quite a bit, though.  Pretty certain I will be switching up the choice of fonts, though I do really like the look of Calluna.  I think the typography was definitely one of the things that made your site stand out as a good thing to use as a basis for mine.  My current plan is to use some popular google fonts for now, with the hope that they are already cached in the visitor's browser.  It's been a bit of a struggle to configure something that looks nearly as good.  It can be hard to view things with fresh eyes, though.

**Pull request closed without merging**
